#Author: Haley Boyan
#Review problem 4: write a function that calculates summary statistics for distributions.
import numpy as np

#Accept two arguments: first the i variable generated by the outside for loop and
#second the numbers list that contains the set of numbers.
def statsum(i,numlist):
    #Print a string indicating what i currently is, like so:
    print("i is currently: %i" %i)
    #Calculate, without using numpy, the mean.
    mean = sum(numbers)/len(numbers)
    #Calculate the median of numbers using np.median().
    median = np.median(numbers)
    #Print the mean and median like so:
    print("mean: %f" %mean)
    print("median: %i" %median)

#You should define your function outside of the provided for loop,
#and then call it with i and numbers within the for loop

# Provided for loop for i and numbers:
for i in range(1, 15, 2):
#assigns i from 1 to 15 with a step size of 2
    numbers = [round(abs(x*np.random.randn())) for x in np.random.gamma(i, i, 100)]
    #created with a list comprehension: an alternative to looping
    #creates a new list from elements of another list
    #np.random.randn() generates a uniform random number between 0 and 1.
    #np.random.gamma(i, i, 100) generates 100 samples from a gamma distribution
        #with mean i and standard deviation i.
    statsum(i,numbers)
